//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.LocalizationStrings", typeof(LocalizationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information system of parking regulations.
        /// </summary>
        public static string Application_HeaderText {
            get {
                return ResourceManager.GetString("Application_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Act date.
        /// </summary>
        public static string DecreeView_ActDate_ColumnHeaderText {
            get {
                return ResourceManager.GetString("DecreeView_ActDate_ColumnHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car number.
        /// </summary>
        public static string DecreeView_CarNumber_ColumnHeaderText {
            get {
                return ResourceManager.GetString("DecreeView_CarNumber_ColumnHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evacuation address.
        /// </summary>
        public static string DecreeView_EvacuationAddress_ColumnHeaderText {
            get {
                return ResourceManager.GetString("DecreeView_EvacuationAddress_ColumnHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evacuation date.
        /// </summary>
        public static string DecreeView_EvacuationDate_ColumnHeaderText {
            get {
                return ResourceManager.GetString("DecreeView_EvacuationDate_ColumnHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regulation list.
        /// </summary>
        public static string DecreeView_HeaderText {
            get {
                return ResourceManager.GetString("DecreeView_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruling number.
        /// </summary>
        public static string DecreeView_Number_ColumnHeaderText {
            get {
                return ResourceManager.GetString("DecreeView_Number_ColumnHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        public static string DecreeView_Payment_PaidText {
            get {
                return ResourceManager.GetString("DecreeView_Payment_PaidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpaid.
        /// </summary>
        public static string DecreeView_Payment_UnpaidText {
            get {
                return ResourceManager.GetString("DecreeView_Payment_UnpaidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment status.
        /// </summary>
        public static string DecreeView_PaymentStatus_ColumnHeaderText {
            get {
                return ResourceManager.GetString("DecreeView_PaymentStatus_ColumnHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        public static string DecreeView_Photos_ColumnHeaderText {
            get {
                return ResourceManager.GetString("DecreeView_Photos_ColumnHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        public static string DecreeView_Place_ColumnHeaderText {
            get {
                return ResourceManager.GetString("DecreeView_Place_ColumnHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every year the number of car owners in Kharkiv increases, which, unfortunately, leads to an increase in the number of violations of parking rules. Parking inspectors use photo to record violations, make a decision on the spot to bring the violator to administrative responsibility. This service provides information about the vehicle number, date and time of the report, a photo of the vehicle, as well as the status of payment of the fine. The purpose of this work is to collect and process data recorded by the [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MainView_DescriptionText {
            get {
                return ResourceManager.GetString("MainView_DescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Notification_Button_Text {
            get {
                return ResourceManager.GetString("Notification_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database loading.
        /// </summary>
        public static string Notification_Primary_Loading {
            get {
                return ResourceManager.GetString("Notification_Primary_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This may take a few minutes. Please wait..
        /// </summary>
        public static string Notification_Secondary_Loading {
            get {
                return ResourceManager.GetString("Notification_Secondary_Loading", resourceCulture);
            }
        }
    }
}
